Added support for fixed salt encryption/decryption
LucasSloan/passwordbasedencryption pull request #2
Opened 2019-07-20 08:47 UTC by cll0ud

Added two new functions for encryption and decryption using fixed salt instead of random salt. Also added a few tests including the case I had posted on my issue (encrypted using Jasypt).

2019-07-20 17:56 UTC, LucasSloan requested changes

2019-07-20 17:56 UTC, LucasSloan commented on pbewithmd5anddes.go
> +func EncryptWithFixedSalt(password string, obtenationIterations int, plainText string, fixedSalt string) (string, error) {
Could you make a helper function that this and Encrypt both call?

2019-07-20 17:56 UTC, LucasSloan commented on pbewithmd5anddes.go
> +func DecryptWithFixedSalt(password string, obtenationIterations int, cipherText string, fixedSalt string) (string, error) {
Same for this and Decrypt.

2019-07-20 20:17 UTC, cll0ud commented
Done! I hope that was what you meant.

2019-07-20 21:45 UTC, LucasSloan requested changes

2019-07-20 21:45 UTC, LucasSloan commented on pbewithmd5anddes.go
> +    if fixedSalt == "" {
Instead of the if statement here, could you move the is logic into the specific functions?

2019-07-20 21:45 UTC, LucasSloan commented on pbewithmd5anddes.go
> +    if fixedSalt == "" {
Ditto

2019-07-20 21:45 UTC, LucasSloan commented on pbewithmd5anddes.go
> +    if fixedSalt == "" {
Ditto

2019-07-20 23:09 UTC, LucasSloan requested changes
Could you fix the indenting so the diff isn't crazy?

2019-07-20 23:10 UTC, cll0ud commented
I don't know why this happened, my IDE ran gofmt. I'll make it right

2019-07-20 23:22 UTC, cll0ud commented
Will it break this thread if I just reset these two last commits to fix it?

2019-07-20 23:36 UTC, cll0ud commented
Ok, now its correct. Sorry for the confusion, Goland was running gofmt in the background. It looks correct on my end, I don't know why diff got crazy like that.

2019-07-20 23:45 UTC, LucasSloan approved these changes

2019-07-20 23:45 UTC, merged

2019-07-20 23:45 UTC, LucasSloan commented
Thanks for the PR!

2019-07-21 00:02 UTC, cll0ud commented
Happy to contribute :)